CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT,
AGE INT NOT NULL,
CITY VARCHAR(50)
);
INSERT INTO STUDENT1
(ID,NAME,MARKS,AGE,CITY)
VALUES
(56,"KARAN",65,16,"PUNE"),
(57,"MAHI",78,17,"DELHI"),
(58,"RON",98,15,"MUMBAI"),
(59,"HOB",35,16,"DELHI"),
(60,"CAREL",93,17,"PUNE"),
(61,"TONY",82,16,"MUMBAI"),
(62,"ALICE",65,15,"PUNE"),
(63,"ALLY",33,15,"MUMBAI");

SELECT * FROM STUDENT;

ALTER TABLE STUDENT
DROP COLUMN CITY;

ALTER TABLE STUDENT
ADD COLUMN CITY VARCHAR(50);

ALTER TABLE STUDENT
CHANGE COLUMN CITY ADDRESS VARCHAR(50);

ALTER TABLE STUDENT
RENAME TO STUDENT1;
SELECT * FROM STUDENT1;

TRUNCATE TABLE STUDENT1;