CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT(
STUD_ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT
);
INSERT INTO STUDENT
(STUD_ID,NAME,AGE)
VALUES
(63,"ADAM",14),
(64,"BOB",14),
(65,"ALICE",15),
(66,"CASEY",13),
(67,"HOB",15);

CREATE TABLE COURSE(
STUD_ID INT,
LANGUAGE VARCHAR(50)
);
INSERT INTO COURSE
(STUD_ID,LANGUAGE)
VALUES
(63,"ENGLISH"),
(68,"HINDI"),
(66,"SANSKRIT"),
(67,"PUNJABI");

SELECT *
FROM STUDENT AS A 
LEFT JOIN COURSE AS B
ON A.STUD_ID = B.STUD_ID
WHERE B.STUD_ID IS NULL;

SELECT *
FROM STUDENT AS A 
RIGHT JOIN COURSE AS B
ON A.STUD_ID = B.STUD_ID
WHERE A.STUD_ID IS NULL;