CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT(
STUD_ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT
);
INSERT INTO STUDENT
(STUD_ID,NAME,AGE)
VALUES
(63,"ADAM",14),
(64,"BOB",14),
(65,"ALICE",15),
(66,"CASEY",13),
(67,"HOB",15);

CREATE TABLE COURSE(
STUD_ID INT,
LANGUAGE VARCHAR(50)
);
INSERT INTO COURSE
(STUD_ID,LANGUAGE)
VALUES
(63,"ENGLISH"),
(68,"HINDI"),
(66,"SANSKRIT"),
(67,"PUNJABI");

SELECT *
FROM STUDENT AS S
INNER JOIN COURSE AS C
ON S.STUD_ID = C.STUD_ID;

SELECT * 
FROM STUDENT
LEFT JOIN COURSE
ON STUDENT.STUD_ID = COURSE.STUD_ID;

SELECT * 
FROM STUDENT
RIGHT JOIN COURSE
ON STUDENT.STUD_ID = COURSE.STUD_ID;