CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT,
CITY VARCHAR(50)
);
INSERT INTO STUDENT
(ROLLNO,NAME,MARKS,CITY)
VALUES
(63,"ADAM",98,"PUNE"),
(64,"BOB",52,"MUMBAI"),
(65,"ALICE",86,"PUNE"),
(66,"CASEY",91,"PUNE"),
(67,"HOB",63,"DELHI"),
(68,"FARAH",78,"DELHI"),
(69,"CHETAN",85,"DELHI");

SELECT NAME,MARKS
FROM STUDENT 
WHERE MARKS > (SELECT AVG(MARKS) FROM STUDENT);

SELECT NAME,ROLLNO
FROM STUDENT
WHERE ROLLNO IN (SELECT ROLLNO FROM STUDENT WHERE ROLLNO%2=0);

CREATE VIEW VIEW1 AS 
SELECT ROLLNO,MARKS FROM STUDENT;

SELECT * FROM VIEW1;

DROP VIEW VIEW1;