CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(25),
MARKS INT 
);
INSERT INTO STUDENT
(ID,NAME,MARKS)
VALUES
(23,"Hopper",56),
(24,"Caleb",89),
(25,"Stophia",96),
(26,"Olivia",23),
(27,"Ava Patel",85),
(28,"Tony",74);

SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENT
SET MARKS = MARKS +1
WHERE MARKS > 60;

DELETE FROM STUDENT
WHERE MARKS < 30;

SELECT * FROM STUDENT;